<?php
/**
 * Virtual robots.txt.
 *
 * @package EasyRankly
 */

namespace EasyRankly\RobotsTxt;

use EasyRankly\Settings\Settings;

defined( 'ABSPATH' ) || exit;

/**
 * Appends the rules from the settings to the robots.txt generated by WordPress.
 *
 * Core rules (wp-admin, admin-ajax.php) and the core sitemap line stay. Nothing is
 * written to disk: a physical robots.txt file would bypass WordPress entirely.
 */
final class RobotsTxt {

	/**
	 * Hooks the core filter.
	 */
	public function register(): void {
		add_filter( 'robots_txt', array( $this, 'filter' ), 10, 2 );
	}

	/**
	 * Appends the extra rules when the site is visible to search engines.
	 *
	 * @param mixed $output robots.txt built so far.
	 * @param mixed $is_public Whether the site is visible to search engines.
	 * @return mixed
	 */
	public function filter( $output, $is_public ) {
		$rules = trim( (string) Settings::value( 'robots_txt' ) );

		if ( ! is_string( $output ) || ! $is_public || '' === $rules ) {
			return $output;
		}

		return rtrim( $output, "\n" ) . "\n\n" . str_replace( "\r", '', $rules ) . "\n";
	}
}
